version: 2
project_name: nobl9-language-server

builds:
  - main: ./cmd/nobl9-language-server
    env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X github.com/nobl9/nobl9-language-server/internal/version.BuildVersion={{ .Version }} -X github.com/nobl9/nobl9-language-server/internal/version.BuildGitBranch={{ .Branch }} -X github.com/nobl9/nobl9-language-server/internal/version.BuildGitRevision={{ .ShortCommit }}'
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: '{{ .ProjectName }}'

archives:
  - formats:
      - binary
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}'

checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}.sha256'
  algorithm: sha256

release:
  make_latest: false
  draft: true
  replace_existing_draft: false
  prerelease: auto
  github:
    owner: nobl9
    name: nobl9-language-server
