// Package sdkdocs defines a [Docs] provider which can be used to interact with
// structured documentation generated by [Nobl9 SDK].
//
// [Nobl9 SDK]: https://github.com/nobl9/nobl9-go
package sdkdocs
